version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - ./storage:/var/www/html/storage
      - ./.env:/var/www/html/.env:ro
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=project_management
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel_password
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_EXTERNAL_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=project_management
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel
    restart: unless-stopped
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=laravel
      - PMA_PASSWORD=laravel_password
    depends_on:
      - mysql
    networks:
      - laravel
    restart: unless-stopped

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local